title: ICO Saifas Tokensale Website
email: jekyll@saifas.info
description: ICO Saifas Tokensale Website
baseurl: ""
url: ""

plugins:
  - jekyll-feed

contents_root_path: /contents/
contents_pages_path: /contents/pages/

source: ./

destination: ../app-build-static

layouts_dir: ./templates/_layouts/